### ISSUE TITLE
Error on credx_set_default_logger Raspberry PI 4

### ISSUE THREAD

**Issue by biagioboi** [hyperledger/indy-shared-rs#41]
I have tried to install aires-cloudagent-python on Raspberry Pi 4 (ARM Cortex-A53 processor) by manually building libraries for aries-askar indy-credx and indy-vdr. For indy-vdr and aries-askar I do not faced any problem. For indy-credx the compilation is successful.
But when I try to release new credentials or a new scheme I receive an error from the bindings.py wrapper script

<img width="808" alt="Screenshot 2023-09-16 alle 15 50 33" src="https://github.com/hyperledger/indy-shared-rs/assets/49649951/40d0f2e3-c2a4-43ea-8220-98b8f725778c">

Clearly, the exception is caused by the method `do_call()`, which receives as a response from the execution of `credx_set_default_logger` the value `4294967296` instead of receiving 0.

Moreover, I noticed by modifying the code of the function and commenting the row 463 `lib_fn.restype = c_int64`, the return of `credx_set_default_logger` is 0; but since the restype must be set in that way everything else crash.

**Comment by andrewwhitehead** [comment]
It looks like a couple types including ErrorCode are using usize, unlike in the other libraries where we've moved away from that. I'll add a PR to clean up up shortly.

**Comment by andrewwhitehead** [comment]
If you'd like to try the latest version (1.0.3) I believe this should be fixed now.

**Comment by biagioboi** [comment]
Yes, it works! Thank you! ErrorCode seems to be fixed.

Now I'm investigating the credential/schema release. If there are Can I open a new issue or can I write here?

**Comment by andrewwhitehead** [comment]
I would open a new issue if something's not working
