### ISSUE TITLE
Upgrade Rust to 1.70 or as appropriate to address build issues

### ISSUE THREAD

**Issue by swcurran** [hyperledger/indy-shared-rs#47]
See Error here: [https://github.com/hyperledger/indy-shared-rs/actions/runs/7905468437/job/21578169242?pr=46](https://github.com/hyperledger/indy-shared-rs/actions/runs/7905468437/job/21578169242?pr=46)

**Comment by amanji** [comment]
Fixed  by https://github.com/hyperledger/indy-shared-rs/pull/48
